title: Campervan.xyz
description: The campervan life
author: CampervanMan
logo: /static/img/avatar.png
github: https://github.com/ashutosh2k12
about: The campervan resource
disqus_shortname:
google_analytics:
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Videos
      url: /videos/
      icon: fa-video-camera
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

social:
    - icon: fa-facebook
      link: '#'
#    - icon: fa-skype
#      link: '#'
    - icon: fa-twitter
      link: '#'
#    - icon: fa-linkedin
#      link: '#'
#    - icon: fa-stack-exchange
#      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://localhost:4000"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
